name: my_trainings_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_fonts: ^6.2.1
  intl: ^0.20.1
  carousel_slider: ^5.0.0
  defer_pointer: ^0.0.2
  flutter_rating_stars: ^1.1.0
  flutter_widget_from_html: ^0.15.3
  lottie: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/json/



























